name: Vite React.js CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
        working-directory: ./client
        # specify the path to package-lock.json inside the client directory
      - name: Build Application
        run: npm run build
        working-directory: ./client
      - name: Test Application
        run: npm run test
        working-directory: ./client
      - name: Deploy to Production
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./client
          # specify the path to the build directory inside the client directory
